### ISSUE TITLE
Removing vendor versioning again

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/terraform-provider-cloudamqp#100]
Was removed in https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/2 but then restored in https://github.com/cloudamqp/terraform-provider-cloudamqp/commit/c843f306a91a9c7dd46a7576c11857339747c1c3, but according to @tbroden84 we don't need it anymore now that we use the Terraform registry.

**Comment by tbroden84** [comment]
[Remove vendor folder again](https://github.com/cloudamqp/terraform-provider-cloudamqp/commit/73146d58e2eb41342c51720a5ba05f99ecbcf789). No issue to build it locally when using `go mod tidy` instead of `go mod vendor`.
