### ISSUE TITLE
Main.tf present under sample/alarm is not correct

### ISSUE THREAD

**Issue by vrathore18** [cloudamqp/terraform-provider-cloudamqp#101]
Could someone please check this sample file. It's not working and I see some errors on it.
https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/master/sample/alarm/main.tf

For example. 
Line no 16: cloudamqp_notificaion
This is a typo. It should be "notification"

line no 39: instance_id = cloudamqp_instance.instance.id
This should be instance_id = cloudamqp_instance. rmq_bunny.id

Line no 59: recipients      = [cloudamqp_notification.recipient_01.id, cloudamqp_notification.recipient_02]
it should be cloudamqp_notification.recipient_02.id 

and many more.

**Comment by dentarg** [comment]
Solved by https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/104
