### ISSUE TITLE
cloudamqp_instance node field deprecated

### ISSUE THREAD

**Issue by heydonovan** [cloudamqp/terraform-provider-cloudamqp#102]
Can we call this out here? https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/instance

Just took me a minute to understand plan vs node, but it's more obvious on this page: https://docs.cloudamqp.com/ under the "Create an Instance" header.

**Comment by dentarg** [comment]
Thanks, I think https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/instance will be updated with the next release of this provider.
