### ISSUE TITLE
firewall rules overriden

### ISSUE THREAD

**Issue by mced** [cloudamqp/terraform-provider-cloudamqp#103]
When the terraform applies its firewall rules, it erases the current rules on cloudamqp instance without telling the inconsistency. Is there a way to notify when a such behavior occurs?

**Comment by tbroden84** [comment]
We have had some issues when dealing with the rules. But the workflow should be that, all rules specified in the module file is used when applying the rules. Terraform should automatically detect if there are any rules added or deleted, and from there apply the rules if necessary.

**Comment by dentarg** [comment]
@mced are you importing the rules before starting to manage them with Terraform?

**Comment by mced** [comment]
@dentarg I double-checked and it works now, terraform detects drifts. I guess that something changed from the cloudamqp API...

**Comment by dentarg** [comment]
@mced great! Yes a bug was fixed in the backend yesterday
