### ISSUE TITLE
Failed to create instance region setting is fialed. 

### ISSUE THREAD

**Issue by hareshdk19** [cloudamqp/terraform-provider-cloudamqp#105]
Hi

I am trying to procure a new instance with  terraform and it is failing with the following error 

Error: CreateInstance failed, status: 422, message: map[error:Invalid region name]
with cloudamqp_instance.instance
on cloudamqp.tf line 17, in resource "cloudamqp_instance" "instance":

We tried various options provided on the website for the regions stuff but all of them failed. Can you provide me with the correct list ?
https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/guides/info_region

I tried all the options but the request if failing with regions stuff and it’s a mandatory parameters.

**Comment by dentarg** [comment]
@hareshdk19 can you share your full cloudamqp.tf file? of course please redacted any credentials or otherwise sensitive information before posting it here

**Comment by hareshdk19** [comment]
terraform {
  required_providers {
    cloudamqp = {
      source = "cloudamqp/cloudamqp"
      version = "1.9.2"

    }
  }
}

# Configure the CloudAMQP Provider
provider "cloudamqp" {
   apikey        =  "Removed it for safety"
}

# Create a new cloudamqp instance
resource "cloudamqp_instance" "instance" {
  name          = "mi-dev-esb-rabbitmq"
  plan          = "bunny-1"
  region        = "azurerm::west-europe"
  nodes         = 1
  tags          = [ "new mi instance" ]
  rmq_version   = "3.8.3"
}

# New recipient to receieve notifications
resource "cloudamqp_notification" "recipient_01" {
  instance_id = cloudamqp_instance.instance.id
  type        = "email"
  value       = ***@***.******@***.***>
  name        = "alarm"
}

# New cpu alarm
resource "cloudamqp_alarm" "cpu_alarm" {
  instance_id     = cloudamqp_instance.instance.id
  type            = "cpu"
  value_threshold = 90
  time_threshold  = 600
  enabled         = true
  recipients      = [cloudamqp_notification.recipient_01.id]
}

# Configure firewall
resource "cloudamqp_security_firewall" "firewall" {
  instance_id = cloudamqp_instance.instance.id
  rules {
    ip = "10.128.18.0/27"
    ports = [5671]
    services = ["AMQPS"]
  }
}

// # Cloudwatch logs integration
// resource "cloudamqp_integration_log" "cloudwatchlog" {
//   instance_id = cloudamqp_instance.instance.id
//   name = "cloudwatchlog"
//   access_key_id = var.aws_access_key
//   secret_access_key = var.aws_secret_key
//   region = var.aws_region
// }

// # Cloudwatch metrics integration
// resource "cloudamqp_integration_metric" "cloudwatch" {
//   instance_id = cloudamqp_instance.instance.id
//   name = "cloudwatch"
//   access_key_id = var.aws_access_key
//   secret_access_key = var.aws_secret_key
//   region = var.aws_region
// }

**Comment by dentarg** [comment]
@hareshdk19 I see that you have specified `azurerm::west-europe` as the region but that isn't a valid option it should be `azure-arm::westeurope` I think

You can use our API to list all the available regions: https://docs.cloudamqp.com/#regions

It looks like https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/guides/info_region maybe need some updating, I'll look into it

**Comment by hareshdk19** [comment]
Yes this resolved the issue.
