### ISSUE TITLE
Requesting darwin_arm64 build

### ISSUE THREAD

**Issue by qnm** [cloudamqp/terraform-provider-cloudamqp#106]
I'm working on my laptop today and noticed that there's not a build for darwin_arm64.

Can I request you add one, please?

Thanks.

**Comment by dentarg** [comment]
Hmm, we have both darwin and arm64 in https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/d05f7a1a8c391757a4512b7d5c0ec48b81c01961/.goreleaser.yml#L18-L24

Not sure what more needs to be done. @tbroden84 @antondalgren do you know?

**Comment by qnm** [comment]
@dentarg This is just a guess as I'm not a GO coder, but I think support was added as of 1.16, and it appears the release action uses 1.14

https://github.com/kvrhdn/terraform-provider-honeycombio/blob/cb397023739997e0cf00c0ab2a515b6bca2e31a7/.github/workflows/goreleaser.yaml#L25

**Comment by dentarg** [comment]
@qnm good catch! that might be it, just gonna test things out locally with Go 1.16 some
