### ISSUE TITLE
Error using nodes datasource

### ISSUE THREAD

**Issue by leetrout** [cloudamqp/terraform-provider-cloudamqp#107]
When trying to use the nodes datasource it appears to be calling an undocumented API endpoint `api/instances/<id>/nodes` and the data returned from that does not match the provider schema...

```hcl
data "cloudamqp_nodes" "production" {
  instance_id = cloudamqp_instance.production.id
}
```

We get this error:

```
Error: error setting nodes for resource ####: Invalid address to set: []string{"nodes", "0", "configured"}
```

It also might be worth noting the docs say `nodes` on the instance resource is not required and computed but it seems to report 1 instead of the correct count. Maybe this should be a separate issue?

**Comment by dentarg** [comment]
@leetrout Thanks for reporting, I can see there's a schema mismatch, I hope we can address it shortly

> It also might be worth noting the docs say `nodes` on the instance resource is not required and computed but it seems to report 1 instead of the correct count. Maybe this should be a separate issue?

Yes, please report in a separate issue, it will be easier to adress when it is in its own issue

**Comment by tbroden84** [comment]
@leetrout We have added the missing attribute "configured" and also gone over all validations. To be able to whitelist all fields in the response that we are using and ignore the rest. Created a new release 1.9.4 that contains this update.

**Comment by leetrout** [comment]
Awesome!!! Thank you!!
