### ISSUE TITLE
Nodes on the instance data source is not computing the correct count

### ISSUE THREAD

**Issue by leetrout** [cloudamqp/terraform-provider-cloudamqp#110]
The docs say `nodes` on the [instance data source](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/data-sources/instance) is not required and it is computed but it seems to report 1 instead of the correct count when it is not set.

Our terraform resource definition:

```
resource "cloudamqp_instance" "production" {
  name        = "production"
  plan        = "rabbit-3"
  region      = "amazon-web-services::us-east-1"
  tags        = ["production"]
  rmq_version = "3.8.14"
}
```

Then we used:

```
data "cloudamqp_nodes" "production" {
  instance_id = cloudamqp_instance.production.id
}

output "nodes_from_instance" {
  value = data.cloudamqp_instance.production.nodes
}
```

Which gave this output (where we expected `3`):

```
Changes to Outputs:
  + nodes = 1
```

Split off from #107

**Comment by tbroden84** [comment]
We have now made a new release [v1.11.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.11.0) that contains the update for handling correct number of nodes. Missmatch between our legacy subscription plans that needs nodes attribute to determine number of nodes from our new subscription plans. 

Will close this issue for now, but could be re-open if it still is an issue.
