### ISSUE TITLE
Document reading API Key from Env Variable CLOUDAMQP_APIKEY

### ISSUE THREAD

**Issue by koalalorenzo** [cloudamqp/terraform-provider-cloudamqp#113]
When I define:

```hcl
provider "cloudamqp" {}
```

it is mandatory to specify the `apikey` while I was expecting the provider to check if the environmental variable `CLOUDAMQP_APIKEY` is defined instead. There is no documentation but some snippets that I found are using it. 

With the env variable present, I get this error:

```
The argument "apikey" is required, but no definition was found.
```

**Comment by dentarg** [comment]
Using the `CLOUDAMQP_APIKEY` environment variable works for me, can you provide more info about your set up and what you are trying to do?

I've tried with Terraform v0.14.11 and Terraform v1.0.7 and the latest version (v1.9.4) of this provider.

**Comment by koalalorenzo** [comment]
Sorry it was my bad, It works fine!

But there is no reference about it on the provider page! 😅 
https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs

Maybe, can we keep this issue open to add it? 🙏
