### ISSUE TITLE
CloudAMQP provider is returning inconsistent result for host option when rabbitmq instance is created through terraform

### ISSUE THREAD

**Issue by sig-alamuri** [cloudamqp/terraform-provider-cloudamqp#125]
Hi,
CloudAMQP provider is returning inconsistent result for host option when rabbitmq instance is created through terraform. Earlier created instances have external url returned as part of host field. But newly created instances have their internal address in this field.
Old instance,
```
{
      "mode": "managed",
      "type": "cloudamqp_instance",
      "name": "instance",
      "provider": "provider[\"registry.terraform.io/cloudamqp/cloudamqp\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "dedicated": false,
            "host": "calm-giraffe.rmq.cloudamqp.com",
            "id": "107930",
            "name": "mt-dev-us-east1",
            "no_default_alarms": true,
            "nodes": 1,
            "plan": "bunny-1",
            "ready": null,
            "region": "google-compute-engine::us-east1",
            "rmq_version": "3.8.9"
        }
      ]
    }
```
Newly created instance,
```
{
      "mode": "managed",
      "type": "cloudamqp_instance",
      "name": "instance",
      "provider": "provider[\"registry.terraform.io/cloudamqp/cloudamqp\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "dedicated": false,
            "host": "happy-cobalt-ram.in.rmq3.cloudamqp.com",
            "id": "154461",
            "name": "upgrade-test",
            "no_default_alarms": true,
            "nodes": 1,
            "plan": "bunny-1",
            "ready": null,
            "region": "google-compute-engine::us-east1",
            "rmq_version": "3.8.9"
          }
        }
      ]
    }
```
https://api.cloudamqp.com/console/9954a338-4857-4167-b599-de76fde6ee86/details

We have locked down the provider version in terraform, so this seems to be returned from the cloudamqp backend API.
Are there any new changes from cloudamqp API side?

**Comment by dentarg** [comment]
> Are there any new changes from cloudamqp API side?

Hi, yes, this was adjusted some weeks ago, see this comment: https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/92#issuecomment-950757291

**Comment by sig-abyreddy** [comment]
@dentarg This is a potential change and will impact the existing users. If you could retain the host field to external address and add addtional field for internal address, that would be helpful.
