### ISSUE TITLE
Terraform Provider Development Program review request

### ISSUE THREAD

**Issue by nitrocode** [cloudamqp/terraform-provider-cloudamqp#13]
Hi! Very cool provider and one that we'd like to use at our company.

I'd like to see this provider be officially supported by terraform's `terraform init` and to do that the source has to pass a series of checks

e.g. https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/issues/10

@cgriggs01 could you do an initial review of this repository?

Thank you everyone for all your hard work.

**Comment by mangoye** [comment]
@nitrocode hi, how is it going for the official support?

**Comment by cgriggs01** [comment]
Hi @nitrocode,

This issue slipped by me back in May, my apologies. If you are looking to submit your provider for review and certification through the [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html) you can do so through this [form](https://goo.gl/forms/iqfz6H9UK91X9LQp2). 

We'd be happy to work with you to officialize this Terraform integration.

**Comment by tylerohlsen** [comment]
Any update on this issue?  Has the form been filled out?  Any status on the application?

**Comment by tbroden84** [comment]
The application has not yet been filled out. Will make sure we prioritize this issue and start the process.

**Comment by tbroden84** [comment]
@tylerohlsen The form has now been filled out and sent.

**Comment by cgriggs01** [comment]
Thanks for your submission, I'll begin the review this week and submit any feedback via an issue in this repository.

**Comment by tylerohlsen** [comment]
Hey @cgriggs01,
How goes the review?

**Comment by tbroden84** [comment]
Had earlier some issues getting the acceptance test working. But have reach out for additional feedback. @cgriggs01 Is it possible to have a look at our request?

**Comment by cgriggs01** [comment]
Hi All, 

I submitted the first set of feedback in issue https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/54. We can continue the thread there.

**Comment by tylerohlsen** [comment]
I just onboarded to the new official provider and all is well!  Thank you so much for doing this!  
Is there now a plan to shut down this repository and point everyone to the [new repo](https://github.com/terraform-providers/terraform-provider-cloudamqp/)?  
And for everyone else getting here from Google, here's the [new official documentation](https://www.terraform.io/docs/providers/cloudamqp/index.html)!

**Comment by tbroden84** [comment]
@tylerohlsen sorry for the late reply, back again from my vacation. Good question, for my understanding this repository will still be used by us for developing the provider. Handling issues and PR. Once ready for a new release, request a new official release. Which will be published to the official repository. 

@cgriggs01 please correct me if I'm wrong. Also cannot find the Slack invite, possible to have a new one?

**Comment by tbroden84** [comment]
No longer viable, due to Terraform Registry.
