### ISSUE TITLE
Unable to import alarm

### ISSUE THREAD

**Issue by torbendury** [cloudamqp/terraform-provider-cloudamqp#135]
Hello, we're trying to import the default alarm (that can't be deleted and must be imported+changed) and are constantly failing.

What we're trying to do:

```bash
+ terraform import -var-file=env-vars/dev.tfvars 'module.cloudamqp["de"].cloudamqp_alarm.alarm["notice"]' xxxxxx,awpdoim-awdawdad-awdawdawd
```

```bash
module.cloudamqp["de"].cloudamqp_alarm.alarm["notice"]: Importing from ID "xxxxx,awpdoim-awdawdad-awdawdawd"...
module.cloudamqp["de"].cloudamqp_alarm.alarm["notice"]: Import prepared!
  Prepared cloudamqp_alarm for import
module.cloudamqp["de"].cloudamqp_alarm.alarm["notice"]: Refreshing state... [id=xxxxx,awpdoim-awdawdad-awdawdawd]

���
��� Error: Missing instance identifier: {resource_id},{instance_id}
��� 
��� 
���
```

We've tried **several** combinations of escape-characters which would allow us to split this up, but we can't manage to successfully import it. Are we doing something wrong (PEBCAK) or is this a real bug?

Best regards

**Comment by dentarg** [comment]
Sorry about this, can you email support@cloudamqp.com with the specific details about your account and cluster so we can look into it more closely?

Also, is this the first time you import alarms or have you done it before and it worked well?

**Comment by torbendury** [comment]
Hello, thanks for the quick response. We'll contact support on office hours.

This is the first time we're importing alarms, we used to create our owns, but the default alarm is always fanning out to our on-calls, so we wanted to import and adjust it via TF.

Have a great weekend !

**Comment by dentarg** [comment]
The issue here was not using the correct instance ID (should be an integer)
