### ISSUE TITLE
Custom firewall ports are not captured and trigger re-creation of firewall rules every time

### ISSUE THREAD

**Issue by zeebonk** [cloudamqp/terraform-provider-cloudamqp#137]
This is not the case for firewall rules where only standard services are selected.

**Comment by dentarg** [comment]
Can you explain more? Maybe you need to import firewall rules?

**Comment by zeebonk** [comment]
Hi @dentarg! I had to find a moment to continue with the work that brought this issue to light. Will come back with more details somewhere this week.

**Comment by zeebonk** [comment]
Good news, the issue was resolved with updating the provider to 1.15.1.
