### ISSUE TITLE
Allow configuration of AWS PrivateLink via terraform

### ISSUE THREAD

**Issue by gregoirefra** [cloudamqp/terraform-provider-cloudamqp#142]
Allowing the configuration of AWS PrivateLink via the terraform provider would simplify a lot the integration with AWS and add more security to clusters created via this provider. It would also simplify the process of creating the link since it would eliminate the manual step of copying the data from the CloudAMQP portal and AWS.

**Comment by tbroden84** [comment]
Have now started to look into this.

**Comment by tbroden84** [comment]
Sorry for the delay, support for PrivateLink have now been added to the latest release [v1.20.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.20.0)
