### ISSUE TITLE
Plugin creation timeout after multiple hours

### ISSUE THREAD

**Issue by coupal** [cloudamqp/terraform-provider-cloudamqp#144]
In the past weeks, we've had issues deploying new clusters on CloudAMQP.
While adding the desired plugins, the provider takes multiples hours before timing out with an error.

```
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h6m38s elapsed]
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h6m48s elapsed]
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h6m58s elapsed]
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h7m8s elapsed]
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h7m18s elapsed]
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h7m28s elapsed]
module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0]: Still creating... [26h7m38s elapsed]
```

```
Error: invalid character '<' looking for beginning of value

  with module.sunco_pod27.module.cloudamqp["202203"].cloudamqp_plugin.rabbitmq_event_exchange[0],
  on ../../modules/cloudamqp/cluster_config.tf line 79, in resource "cloudamqp_plugin" "rabbitmq_event_exchange":
  79: resource "cloudamqp_plugin" "rabbitmq_event_exchange" {
```

**Comment by tbroden84** [comment]
@coupal Is it always the same plugin or have you seen this on different plugins too? Will investigate the issue.

**Comment by dentarg** [comment]
@coupal are you able to share your full Terraform definition? Feel free to email it via support if you don't want to share it here. So far we haven't been able to reproduce the issue.

**Comment by coupal** [comment]
I've just sent an email to the support email containing our code.
We are deploying the module 4 times, maybe we it some rate limiting that the provider doesn't handle correctly.

**Comment by dentarg** [comment]
This can happen when you try to enable multiple plugins at the same time. What happens is that the provider issues one CloudAMQP API request per plugin to enable, and Terraform executes these in parallell, so they will be received by our backend at the same time (or very close). These requests are turned into `rabbitmq-plugins enable` commands run on the server and when multiple such commands run at roughly the same time, it looks like the requested plugin isn't always enabled, [but the API responds with 204 No Content as if the plugin was enabled, and the provider then waits until the "list plugins" endpoint reports it is enabled](https://github.com/84codes/go-api/blob/6d563feac409debd5f7aaca5f396e7621bb41ba6/api/plugins.go#L32-L47), which will never happen. We're think how we can address this.

**Comment by tbroden84** [comment]
@coupal After more investigation and testing we have updated our CloudAMQP backend to handle asynchronous requests for both plugin/community. This will handle that Terraform executes the request in parallell and instead handled one by one in the backend. 

There is a new release of the provider [v1.19.2](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.19.2) with updated dependency to support this.
