### ISSUE TITLE
Error when enabling RabbitMQ Delayed Message Plugin

### ISSUE THREAD

**Issue by klaa97** [cloudamqp/terraform-provider-cloudamqp#145]
Hello 👋 

I am having an error while installing the RabbitMQ Delayed Message Plugin.

## Versions

- RabbitMQ 3.9.13
- Erlang 24.1.7
- CloudAMQP Terraform Provider 1.15.2

## Error
When I apply with the following resource:
```
resource "cloudamqp_plugin" "rabbitmq_delayed_message_exchange" {
  instance_id = cloudamqp_instance.rabbit_instance.id
  name        = "rabbitmq_delayed_message_exchange"
  enabled     = true
}
```

I get an error:
```
| Error: json: cannot unmarshal array into Go value of type map[string]interface {}
│
│   with module.common.cloudamqp_plugin.rabbitmq_delayed_message_exchange,
│   on ../../common/cloudamqp/main.tf line 10, in resource "cloudamqp_plugin" "rabbitmq_delayed_message_exchange":
│   10: resource "cloudamqp_plugin" "rabbitmq_delayed_message_exchange" {
```

## Temporary solution
- Enable the plugin in the Admin console manually
- Apply
- It works!

Thank you!

**Comment by tbroden84** [comment]
@klaa97 It's part of the community plugins. So if you try using the plugin community resource it should work. 

`resource "cloudamqp_plugin_community" "rabbitmq_delayed_message_exchange" {
...
} `

**Comment by klaa97** [comment]
@tbroden84  Interesting!

I see though two plugins, one in the plugin section, and the other in the community plugins section (both activated) 🤔 

Community:
<img width="1243" alt="Screenshot 2022-04-05 at 17 57 06" src="https://user-images.githubusercontent.com/39653693/161795731-07f7d96c-7a98-42a6-8b0d-26cde1524b30.png">

Non-Community:
<img width="1278" alt="Screenshot 2022-04-05 at 17 57 27" src="https://user-images.githubusercontent.com/39653693/161795825-fecfe519-43f9-471a-893c-4223df367e9d.png">

It is working now (or so it seems) so I'd be inclined to leave it as-is, but I guess that I could be able to import the community plugin in my terraform resource config, together with the non-community one 🤔

**Comment by tbroden84** [comment]
Ah true, the community plugin gets installed with the managed cloudamqp_plugin_community resource. Then moved over to the rest of the plugins. You could keep the managed cloudamqp_plugin_community resource, will be disabled and uninstall once the resource is removed. 

The workflow could be improved to avoid confusion.

**Comment by gerardc** [comment]
Confirming this behaviour is still present. 

config:
```
resource "cloudamqp_plugin_community" "rabbitmq_delayed_message_exchange" {
  instance_id = cloudamqp_instance.instance.id
  name = "rabbitmq_delayed_message_exchange"
  enabled = true
}
```

Output:
```
cloudamqp_rabbitmq_configuration.cluster_config: Still creating... [40s elapsed]
cloudamqp_rabbitmq_configuration.cluster_config: Still creating... [50s elapsed]
cloudamqp_rabbitmq_configuration.cluster_config: Creation complete after 55s [id=123456]
╷
│ Error: json: cannot unmarshal array into Go value of type map[string]interface {}
│
│   with cloudamqp_plugin_community.rabbitmq_delayed_message_exchange,
│   on plugins.tf line 3, in resource "cloudamqp_plugin_community" "rabbitmq_delayed_message_exchange":
│    3: resource "cloudamqp_plugin_community" "rabbitmq_delayed_message_exchange" {
│
╵
```

From local testing the plugin enable endpoint returns a 204 No Content, which I'm guessing cannot be deserialised into `map[string]interface{}`

@tbroden84 would you accept a PR to address this?

**Comment by tbroden84** [comment]
@gerardc Strange, we use our API wrapper [go-api](https://github.com/84codes/go-api/blob/master/api/plugins_community.go#L37) to handle the API calls. 

As you say the enable endpoint return 204 and return no body. Once triggered we wait and poll the plugin list (not the community one), to make sure it has been enabled. However this call needs to reach the server to fetch the real data and could be the cause of this. 

Feel free to open a PR and I will take a look, we really appreciate your contributions.

**Comment by dentarg** [comment]
We figured out why this is happening today, if the CloudAMQP backend can't reach the server where it should enable the plugin, or it takes time (>28 seconds currently) for some reason, the API will respond with HTTP status 400 and a JSON array as body (`["Timeout talking to backend","Timeout talking to backend","Timeout talking to backend"]`). The provider, or more correctly, the client library the provider uses does not handle this ([src link](https://github.com/84codes/go-api/blob/6d563feac409debd5f7aaca5f396e7621bb41ba6/api/plugins.go#L32-L47)). We're thinking how to best address this.

**Comment by gerardc** [comment]
@dentarg ah that makes sense, thanks for lopping back on this, really appreciate it 👍

**Comment by tbroden84** [comment]
After more investigation and testing we have updated our CloudAMQP backend to handle asynchronous requests for both plugin/community. This will avoid multiple respons back when the server can't be reach. Also makes enabling multiple plugins works much better.   

There is a new release of the provider [v1.19.2](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.19.2) that have updated dependency to our client library [v1.9.1](https://github.com/84codes/go-api/releases/tag/v1.9.1) that enable this.
