### ISSUE TITLE
In code support for Private link to Azure

### ISSUE THREAD

**Issue by Marcus-James-Adams** [cloudamqp/terraform-provider-cloudamqp#154]
Similar to #142 
But for Azure, for the very same reasons - allowing the creation of the cloudamqp side of private link via terraform would remove manual intervention and allow a seamless automated experience.

**Comment by ankek** [comment]
Do we have any estimated date for this important feature?

**Comment by dentarg** [comment]
There's no date but it is on top of the list to be implemented.

**Comment by ankek** [comment]
is there any updates about this feature?

**Comment by tbroden84** [comment]
@ankek Unfortunately not yet.

**Comment by tbroden84** [comment]
@ankek Have now started to look into this.

**Comment by tbroden84** [comment]
Sorry for the delay, support for PrivateLink have now been added to the latest release [v1.20.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.20.0)
