### ISSUE TITLE
Can't import “cloudamqp_vpc_peering” resource

### ISSUE THREAD

**Issue by strund3r** [cloudamqp/terraform-provider-cloudamqp#158]
## Issue
I'm getting this error when trying to import this resource, even though it exists on the [documentation](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/vpc_peering#import)

```sh
$ terragrunt import cloudamqp_vpc_peering.this vpc-xxxxxxxxx

cloudamqp_vpc_peering.this: Importing from ID "vpc-xxxxxxxxx"...

Error: resource cloudamqp_vpc_peering doesn't support import
```

## Versions
* cloudamqp = `1.17.2`
* aws = `3.75.2`

**Comment by tbroden84** [comment]
Then we have missed and added this to the documentation, even though the resource is not importable. It is only used to accept the VPC peering requested from your AWS account. It using our internal CloudAMQP identifiers (vpc_id or instance_id) to make the underlying API calls, together with peering_id created by AWS.

Example:
```
resource "cloudamqp_vpc_peering" "vpc_accept_peering" {
  vpc_id = cloudamqp_vpc.vpc.id
  peering_id = aws_vpc_peering_connection.aws_vpc_peering.id
  sleep = 30
  timeout = 600
}
```

Will update the documentation to be correct.

**Comment by dentarg** [comment]
The documentation now states that you can't import this resource.

**Comment by tbroden84** [comment]
Receiving this issue, since we got a similar request for GCP. With more investigation and internal discussion we found a plausible approach to enable the import.

**Comment by tbroden84** [comment]
New release version [1.32.2](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.32.2) adding the import. Will close this issue again.
