### ISSUE TITLE
Allow data source cloudamqp_vpc_info lookup using name

### ISSUE THREAD

**Issue by muresan** [cloudamqp/terraform-provider-cloudamqp#159]
Allow data source `cloudamqp_vpc_gcp_info` and `cloudamqp_vpc_info` to lookup the `vpc_id` using the VPC `name`.

Currenlty if the VPC is created in an infrastructure deploy pipeline there is no way to discover the `vpc_id` from another pipeline that has access to the same credentials as the ones used to deploy the VPC, the `vpc_id` needs to be passed in one way or another.

Use case:
* deploy resources related to the VPC peering in one pipeline: `cloudamqp_vpc`, `cloudamqp_vpc_gcp_peering`, `google_compute_network_peering` (in the same project or in a shared vpc project) this happens only once for multiple clusters.
* deploy cluster resources using the above VPC peering in other projects that share the same VPC (or not) currently `vpc_id` is not discoverable based on the VPC name which makes this workflow cumbersome, the vpc_id needs to be shared between deploy pipelines.

**Comment by dentarg** [comment]
@muresan Thanks for opening the issue. Have you seen `cloudamqp_account_vpcs`? It was added to address this use-case: https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/v1.18.0/docs/data-sources/account_vpcs.md

**Comment by muresan** [comment]
> 

LGTM

**Comment by dentarg** [comment]
Thanks, can we close this issue? Even if there's a more elegant solution to be had, I think it is unlikely we can prioritise that over other things needing to be done.

**Comment by muresan** [comment]
Sure.
