### ISSUE TITLE
Terraform fails to parse the version from the registry

### ISSUE THREAD

**Issue by riechst1** [cloudamqp/terraform-provider-cloudamqp#167]
Terraform fails to parse the version from the registry. 
Terraform version: 0.12.31
Coudamqp plugin version: 0.8.6 and 1.19.0

Error when planning:
`Error: Failed to install provider

Error while installing -/cloudamqp v1.19.1: could not query provider registry
for registry.terraform.io/-/cloudamqp: registry response includes invalid
version string "1; mode=block": invalid characters "; mode=block"`

Registry response:
`{
      "version": "1.10.0",
      "protocols": [
        "4.0",
        "5.0"
      ],
      "platforms": [
        {
          "os": "darwin",
          "arch": "arm64"
        },
        {
          "os": "linux",
          "arch": "amd64"
        },
        {
          "os": "linux",
          "arch": "arm64"
        },
        {
          "os": "windows",
          "arch": "amd64"
        },
        {
          "os": "darwin",
          "arch": "amd64"
        }
      ]
    },
    {
      **"version": "1.19.1",
      "protocols": [
        "1; mode=block"**
      ],
      "platforms": [
        {
          "os": "linux",
          "arch": "amd64"
        },
        {
          "os": "windows",
          "arch": "arm64"
        },
        {
          "os": "linux",
          "arch": "arm64"
        },
        {
          "os": "darwin",
          "arch": "arm64"
        },
        {
          "os": "darwin",
          "arch": "amd64"
        },
        {
          "os": "windows",
          "arch": "amd64"
        }
      ]
    },`
 
Seems that `1.19.1` is causing the problem.

**Comment by dentarg** [comment]
Looks like a problem with the Terraform registry? Can you post a full reproducer?

**Comment by tbroden84** [comment]
While using Terraform version: 0.12.31, for our latest provider you should get the following error. 

```
Provider "cloudamqp" v1.19.1 is not compatible with Terraform 0.12.31.
...
Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to cloudamqp/cloudamqp. Please update your source in required_providers.
```
And need at least upgrade your Terraform version to 0.13 (from my understanding to even fetch providers from the registry). Note: latest version is 1.27. https://www.terraform.io/language/upgrade-guides

Then change the [required provider](https://www.terraform.io/language/providers/requirements#requiring-providers) section, to pick the latest version.
```
terraform {
  required_providers {
    cloudamqp = {
      source = "cloudamqp/cloudamqp"
      version = "~> 1"
    }
  }
}
```

**Comment by riechst1** [comment]
@dentarg and @tbroden84 I apologize for the late response. I gather more information from the team and the issue happened when migration to 0.13.7. 

Terraform config:
`terraform {
  backend "s3" {
    bucket = "pltsci-infrastructure-tfstate"
  }
  required_providers {
    cloudamqp = {
      source  = "cloudamqp/cloudamqp"
      version = "1.8.6"
    }
    aws = "~> 2.70.0"
  }
}
resource "cloudamqp_instance" "this" {
  name              = var.name
  plan              = var.plan
  region            = var.region
  nodes             = var.nodes
  rmq_version       = var.rmq_version
  tags              = values(local.tags)
  no_default_alarms = var.no_default_alarms

  lifecycle {
    prevent_destroy = true
  }
}


resource "cloudamqp_security_firewall" "this" {
  instance_id = cloudamqp_instance.this.id

  rules {
    ip       = "0.0.0.0/0"
    ports    = [5671]
    services = ["AMQPS"]
  }
}`

The test to migrate from 0.12 to 0.13 worked about 4 - 5 weeks ago, but it started failing  at the time I created the issue.

**Comment by tbroden84** [comment]
Tried downgrading my Terraform version to 0.13.7 and init into a new configuration. Then trying with a bunch of version of our provider and the latest. But cannot reproduce this issue. 

One more thing that looks fishy from your initial post, is the registry path in the error message. 
`registry.terraform.io/-/cloudamqp`

The calls I got from Terraform when fetching/installing the provider is 
`registry.terraform.io/cloudamqp/cloudamqp`

**Comment by riechst1** [comment]
@tbroden84 sorry for the late response. I have tried different versions and still getting the same error. 
How to reproduce:

- Upgrade from terraform 0.12.31 -> 0.13.X with cloudamqp provider version `1.8.6` (any of the minor version is failing for me. But this upgrade step used to work for me a month ago.)
- Using remote state file. See example below
`terraform {
  backend \"s3\" {
    bucket = \"pltsci-infrastructure-tfstate\"
  }
  required_providers {
    cloudamqp = {
      source  = \"cloudamqp/cloudamqp\"
      version = \"1.8.6\"
    }
    aws = \"~> 2.70.0\"
  }
}`

- And I'm also calling a custom model, but the module is basic essentially same code as posted before. 
` module \"cloudamqp\" {
  source                              = \"../../module/cloudamqp\"
  plan                                = var.plan
  nodes                               = var.nodes
  name                                = \"${var.environment}-${var.name}\"
  region                              = var.region
  no_default_alarms                   = var.no_default_alarms
  tags                                = local.tags
  integrations_log_name               = var.integrations_log_name
  datadog_api_key                     = var.datadog_api_key                     
  cloudwatchlog_aws_access_key_id     = var.cloudwatchlog_aws_access_key_id    
  cloudwatchlog_aws_secret_access_key = var.cloudwatchlog_aws_secret_access_key 
  datadog_tags                        = local.datadog_tags
}`
- I'm using partial config to initialize terraform backend 
`terraform init -get=true -backend-config \"key=providers/cloudamqp/${CLOUD_PROVIDER}/${ENVIRONMENT}/tfstate.json\"`

And here is the whole output when I initialize. 
`Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding cloudamqp/cloudamqp versions matching \"1.8.6, >= 1.8.6\"...
- Finding latest version of -/aws...
- Finding latest version of -/cloudamqp...
- Finding hashicorp/aws versions matching \"~> 2.70.0\"...
- Installing cloudamqp/cloudamqp v1.8.6...
- Installed cloudamqp/cloudamqp v1.8.6 (self-signed, key ID D2F4A50F2BA2AFDC)
- Installing -/aws v4.27.0...
- Installed -/aws v4.27.0 (self-signed, key ID 34365D9472D7468F)
- Installing hashicorp/aws v2.70.1...
- Installed hashicorp/aws v2.70.1 (self-signed, key ID 34365D9472D7468F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Warning: Additional provider information from registry

The remote registry returned warnings for registry.terraform.io/-/cloudamqp:
- For users on Terraform 0.13 or greater, this provider has moved to
cloudamqp/cloudamqp. Please update your source in required_providers.


Error: Failed to install provider

Error while installing -/cloudamqp v1.19.1: could not query provider registry
for registry.terraform.io/-/cloudamqp: registry response includes invalid
version string \"1; mode=block\": invalid characters \"; mode=block\"`

**Comment by riechst1** [comment]
@dentarg and @tbroden84 found an github issue and still open in terraform. Here is the link https://github.com/hashicorp/terraform/issues/25819

Thanks again for all the help and I am not sure why that error did happened during my first tests until it was time to do the actual migrations. 😅 

Recap: The issue is when migrating from 0.12.31 -> 0.13.x and the solution is to run
```
terraform state replace-provider -- -/cloudamqp cloudamqp/cloudamqp
```

**Comment by tbroden84** [comment]
@riechst1 Nice find! IIRC, the provider was hosted pre-registry (before 0.13) in a cloned Github repository. So the provider source was not the same back then. 

Also so long ago that I cannot remember if we every tried out upgrading an existing state, or we just managed to get the correct source from the beginning.
