### ISSUE TITLE
Feature Request: Add LavinMQ Instances

### ISSUE THREAD

**Issue by HaukeMarquardt** [cloudamqp/terraform-provider-cloudamqp#169]
Hi,

We'd love to try the new LavinMQ instances! Unfortunately, the Terraform Provider cannot create these.

Do you know if the API can create LavinMQ instances?
If so, can I create a pull request to add it if no one is working on it yet.

**Comment by dentarg** [comment]
Yes, it is possible to create instances on LavinMQ plans with the API. Feel free to contribute a PR!
