### ISSUE TITLE
Feature Request: Support Victorops Recipents 

### ISSUE THREAD

**Issue by sharyanrtr** [cloudamqp/terraform-provider-cloudamqp#178]
The `cloudamqp_notification` resource doesn't seem to support adding Victorops recipients, which requires the `options` parameter as per the cloudAMQP API: https://docs.cloudamqp.com/cloudamqp_api.html#create-recipient.

As an API payload example, it seems we need the `options` parameter to be able to add the routing key for a Victorops integration;

```JSON
{
    "id": 1234567,
    "type": "victorops",
    "value": "20A6F04D-0EBD-47F2-8E5A-154A1834A883",
    "name": "Test VictorOps Integration",
    "options": {
        "rk": "ROUTINGKEY"
    }
}
```

Currently the terraform resource doesn't support this. It would be great if we could so we can manage our on-call system through Terraform.

**Comment by tbroden84** [comment]
@sharyanrtr 

Just released a new version [v1.22.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.22.0) adding the options parameter to allow using routing key for Victorops notification recipient.

```hcl
resource "cloudamqp_notification" "victorops_recipient" {
  instance_id = cloudamqp_instance.instance.id
  type        = "victorops"
  value       = "<UUID>"
  name        = "Victorops"
  options     = {
    "rk" = "ROUTINGKEY"
  }
}
```
