### ISSUE TITLE
Feature Request: `cloudamqp_extra_disk_size` for other cloud providers

### ISSUE THREAD

**Issue by torbendury** [cloudamqp/terraform-provider-cloudamqp#180]
Currently, according to [the docs](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/extra_disk_size), extra disk space is only available for dedicated instances hosted on AWS. I'm hosting on GCP/Azure and miss this feature.

Without it, the only way to gain more disk space is by increasing the overall instance size which introduces unneccesary costs and dead resources (CPU/Mem).

**Comment by dentarg** [comment]
It is possible to add extra disk space in other clouds using the web console at https://customer.cloudamqp.com/instance (it may include downtime)

**Comment by philipp-hb** [comment]
@dentarg any news on this? Clicking is quite a bad workflow

**Comment by dentarg** [comment]
@philipp-hb No news, and I agree with you. Do you mind share what company/companies you represent? (You can email support and reference this issue if you don't want to do that here)

**Comment by tbroden84** [comment]
There is still updates needed in our backend before we can proceed with adding this. But will start looking into this again.
