### ISSUE TITLE
Feature Request: configure AWS EventBridge integration

### ISSUE THREAD

**Issue by hoyon** [cloudamqp/terraform-provider-cloudamqp#188]
Right now these can either be created in the cloudamqp console or via the API. It would be great if we could use terraform to manage them instead!

**Comment by tbroden84** [comment]
Thanks for the issue, will add this to our inbox to look at.

**Comment by tbroden84** [comment]
@hoyon Just released a new. version [v1.24.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.24.0) adding this feature. Please take a look at the new resource: https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/integration_aws_eventbridge
