### ISSUE TITLE
[Bug] data cloudamqp_notification broken after 1.22.0 changes

### ISSUE THREAD

**Issue by ralbertazzi** [cloudamqp/terraform-provider-cloudamqp#199]
Given this Terraform definition:
```hcl
data "cloudamqp_notification" "slack" {
  name        = "slack"
  instance_id = module.common.cloudamqp_instance.id
}
```

When upgrading the Terraform provider to a version `>= 1.22.0` I get this error on apply:
```
╷
│ Error: error setting options for resource <REDACTED>: Invalid address to set: []string{"options"}
│ 
│   with data.cloudamqp_notification.slack,
│   on alerts.tf line 5, in data "cloudamqp_notification" "slack":
│    5: data "cloudamqp_notification" "slack" {
│ 
╵
```

It looks clearly related to this change: https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/185

**Comment by dentarg** [comment]
Yes, I guess we need to handle the `options` map here, not try to set it like a regular key with a value

https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/78d7b7a67a530244efe864b92c11b58297edf716/cloudamqp/resource_cloudamqp_notification.go#L98-L100

cc @tbroden84

**Comment by dentarg** [comment]
Or is it `nil` so it should be skipped? I assume #185 worked when `options` was used in create/update

**Comment by tbroden84** [comment]
@ralbertazzi do you only get this when using the data source? Or also the resource? 

Tried to reproduce it with the data source (which currently missing the options map) for multiple types. All my data reads was successful. Did my tries with a locally built copy of the v1.24.2 build.

**Comment by tbroden84** [comment]
Not sure how I failed to reproduce this last time. Was just the extra options attribute missing as pointed out. Will include the fix in the next release.
