### ISSUE TITLE
Import existing clusters

### ISSUE THREAD

**Issue by nitrocode** [cloudamqp/terraform-provider-cloudamqp#20]
Would be nice to be able to import existing clusters to backport configs to terraform

**Comment by jwierzbo** [comment]
i've added such a support in my version of provider: https://github.com/jwierzbo/terraform-provider-cloudamqp

**Comment by nitrocode** [comment]
Can you PR that in to this official one?

**Comment by tbroden84** [comment]
Added import functionality for current resources. Instead of using @jwierzbo approach with secondary api key. Alarm and notification/recipient also needs the instance id.
