### ISSUE TITLE
Support for partner-subscribed partial api handling

### ISSUE THREAD

**Issue by arthmoeros** [cloudamqp/terraform-provider-cloudamqp#204]
Hi!

We have subscribed two CloudAMQP instances through Azure Marketplace, I'm aware that `customer` api (https://customer.cloudamqp.com) is not supported in our case, but I understand that the `api` api (https://api.cloudamqp.com) should be supported by this provider, as this documentation for the `api` one offers Terraform managing  https://docs.cloudamqp.com/cloudamqp_api.html .

I wanted to manage alarms, recipients and firewall rules via Terraform, however, after a while struggling with the provider and diving in this repository source code and the [go-api](https://github.com/84codes/go-api) one, because I didn't understand what was wrong, I realized that the url building for api calls is tightly coupled with the customer api url structure ([example](https://github.com/84codes/go-api/blob/8ea1f2dea67aadcc917b6abcb629cd3434a2bfe3/api/security_firewall.go#L57)), so even when I found out the "baseurl" provider arg, it was proven ineffective because I get a `401` error even if I set the baseurl to `https://api.cloudamqp.com` and `apikey` is valid.

This renders the provider not suitable for customers without access to the customer api, which I understand is not targeted for partner-subscribed instances, but we should be able to manage alarms, firewall, etc...

Is this going to be handled?, in the meantime I'll have to manage with null_resource executing curl or even a quick patched version of the whole provider along the go-api library in our case.

I would like to know so I can reach a decision on the latter.

Cheers!

**Comment by tbroden84** [comment]
Hi, 

The initial design for this provider have been focused on our customers managed by us and been further developed in that direction. We have had briefly internal discussions to go over the design, to also make it possible to use the provider from the different marketplaces that we use. A final decision have not yet been taken.

To clarify, true we have two different APIs.
`customer` api https://customer.cloudamqp.com requires an account based API key. As you mention all resources/data sources are tightly coupled to having a CloudAMQP instance created and our client library makes all request through the `customer` api. 

`api` api https://api.cloudamqp.com requires a CloudAMQP instance API key (also provided for marketplaces) to make valid requests. Which the provider currently not is design for.

**Comment by dentarg** [comment]
We are aware of this shortcoming and are working towards addressing it. We'll update this issue when we have news to share.

**Comment by arthmoeros** [comment]
thanks for your replies!

@dentarg the Terraform support advertised in the `api` docs was a factor in subscribing both SaaS (that we are migrating our own IaaS implementation to, so is only gonna grow more), gotta say I was a bit disappointed to find this situation. Is this on any roadmap?, Is this considered to be taken current year?, next year?

Nevertheless, I think the docs should be updated to reflect this current situation, I did waste so much time preparing my terraform files and trying to make them work in vain.

I will manage with null_resource+curl for now, would like to know if this would be addressed current year or later.

**Comment by dentarg** [comment]
We are currently working on it, so this year is very likely.

It is a good suggestion to note this in the API documentation.

I'm curious, being a direct customer isn't an option for you?

**Comment by arthmoeros** [comment]
> We are currently working on it, so this year is very likely.

Thanks! 

> 
> It is a good suggestion to note this in the API documentation.
> 
> I'm curious, being a direct customer isn't an option for you?

Yeah, at least for now is not an option.

We do have a huge contract with Azure, so we take advantage of the "whole package" of credits within the contract to include the CloudAMQP subscriptions from Marketplace.

**Comment by oskgu360** [comment]
Hey!

We have released a new marketplace offering/integration which integrates the marketplace with the `customer.cloudamqp.com` application directly, enabling the full feature set in order to use terraform properly with us.

 [Azure marketplace link](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/84codes.cloudamqp-v4?tab=Overview)
 
Please check it out, if set up and suits your need, we can transfer current instances seamless to the new integration. Contact support@cloudamqp.com if that is the case!
