### ISSUE TITLE
Proposal: support plugins in the provider definition

### ISSUE THREAD

**Issue by bdubaut** [cloudamqp/terraform-provider-cloudamqp#22]
CloudAMQP supports a few toggles to enable/disable some plugins such as `rabbitmq_amqp1_0` on a RabbitMQ instance. It would be very handy to be able to declare these in the Terraform provider. I'm not sure how it would look like in terms of instance schema, but that is something that would allow the users of the providers to truly version their RabbitMQ infrastructure through Terraform.

_I did not find this option to be supported by the CloudAMQP HTTP API, which may explain why this is not supported, so I don't know if this is doable anytime soon._

**Comment by tbroden84** [comment]
Enabled support for both plugins and community plugins. Created a datasource for both, using this makes it possible to list all plugins and community plugins, with name and their status. 

Further I also added a resource, makes it possible to enable/disable a specific plugin. 
For more information see https://docs.cloudamqp.com/cloudamqp_terraform.html
