### ISSUE TITLE
[Feature request] Flag to disable cloudamqp_vpc_gcp_peering wait for peering request to be accepted

### ISSUE THREAD

**Issue by Unb0rn** [cloudamqp/terraform-provider-cloudamqp#226]
It would be nice to have a flag (or even a default behavior) making cloudamqp_vpc_gcp_peering resource stop waiting for peering to get "Connected" status.
It may be convenient to set such a flag if GCP infra is handled from outside of the tf code/module. 
Also the majority of other cloud providers allow to create the peering only form one side without checking the peering state.

**Comment by tbroden84** [comment]
Sounds reasonable and thanks for the request, will look into adding this.

**Comment by tbroden84** [comment]
Feature released in https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.28.0
