### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by Developer2048** [cloudamqp/terraform-provider-cloudamqp#23]
`root@test:~/go/src/github.com/cloudamqp/terraform-provider$ make init
linux

GOOS=linux GOARCH= go build -o terraform-provider-cloudamqp
# github.com/cloudamqp/terraform-provider/vendor/github.com/84codes/go-api/api
vendor/github.com/84codes/go-api/api/api_alarms.go:6:2: imported and not used: "time"
vendor/github.com/84codes/go-api/api/api_alarms.go:31:2: not enough arguments to return
	have (string)
	want (map[string]interface {}, error)
vendor/github.com/84codes/go-api/api/customer_instance.go:15:35: New redeclared in this block
	previous declaration at vendor/github.com/84codes/go-api/api/api.go:15:35
Makefile:30: recipe for target 'build' failed
make: *** [build] Error 2`

I tried to build this on Ubuntu 18.04 and a colleague on MacOS. It failed in both cases.

**Comment by spider-network** [comment]
I have the same Issue ;-(

When I modify the Gopkg.toml than the compile process works, but then I got an error at the runtime:

*Gopkg.toml*
```
[[constraint]]
  branch = "master"
  name = "github.com/84codes/go-api"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.14"
```

*Exception*
```
Error: provider.cloudamqp: fork/exec /........./cloudamqp/.terragrunt-cache/t6Pgja4t7yzrMKyL6_v936Z4VFw/dYUpmOXd4-mj-lD70q0ri6jyspA/terraform-provider-cloudamqp: exec format error
```

Please can you provide compiled cloudamqp providers?

+1 for https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/7

**Comment by tbroden84** [comment]
Looks like Makefile pointed to my local branch, have pushed an update for that. Also created and initial release with the compiled binary.

**Comment by spider-network** [comment]
Cool, the provided release works for me

**Comment by spider-network** [comment]
@tbroden84 Is it possible that you push this provider also to hashicop in the future?

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "cloudamqp" not available for installation.
```

Until that it would be great to have a release with the tagging feature ;-)

**Comment by spider-network** [comment]
@tbroden84 The provider in the release is not compiled for Linux ;-( When you are pushing a new release, can you provide a darwin and Linux version? Please, can you bump a new version?

**Comment by tbroden84** [comment]
@spider-network Did a cross-compile of the v1.0.0 source code and uploaded it. Tried it out in Linux environment and worked for me at least. Please try it out.

**Comment by spider-network** [comment]
Thx can you bump a version with the tag feature, please v1.1.0?

**Comment by tbroden84** [comment]
@spider-network Have now released v.1.1.0.
