### ISSUE TITLE
`cloudamqp_instance`: remove the `api.DefaultRmqVersion()` call

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/terraform-provider-cloudamqp#236]
In which situations are we fetching the default RabbitMQ version?

Do we need to do it? / What happens if we don't?

https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/18de509d78e24b1c6b1f486a1f32168e1f99edb4/cloudamqp/resource_cloudamqp_instance.go#L181-L183

**Comment by dentarg** [comment]
Thanks for checking, what I suspected. We should remove it then :)

**Comment by tbroden84** [comment]
Nice catch!

**Comment by tbroden84** [comment]
Available in [v1.29.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.29.0)
