### ISSUE TITLE
Inconsistency in docs (`cloudamqp_integration_metrics` vs `cloudamqp_integration_metric`)

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/terraform-provider-cloudamqp#239]
Feedback received:

> In the sidebar and the URL of the resource is given as plural, but the examples and what the provider accepts is just the singular variant.
> 
> See: https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/integration_metrics note the s at the end.

**Comment by dentarg** [comment]
I think we need to rename [`integration_metrics.md`](https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/d972e2c3d60194679f90f4b64e0539d3285fc25c/docs/resources/integration_metrics.md) to `integration_metric.md` to make it consistent.

However, doing so would render https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/integration_metrics a 404 in the future. We could avoid that by keeping a file named `integration_metrics.md` that just say you should look at the `cloudamqp_integration_metric` page.

**Comment by tbroden84** [comment]
Cannot find any reference to `../intergration_metrics.md` in the other pages. Should be ok to just rename to `cloudamqp_integration_metric`.
