### ISSUE TITLE
GCP VPC Peering - Error creating 2nd peer connection

### ISSUE THREAD

**Issue by mpichette** [cloudamqp/terraform-provider-cloudamqp#242]
We have two GCP projects we're trying to peer to a single CloudAMQP instance/VPC. The first peer request goes through fine but the second one fails with the following error:

`Error: request VPC peering failed, status: 400, message: map[error:There is already a peering with the same name. Enter a different name.]`

The only thing that immediately comes to mind looking at the output of the first (successful) peer request is the generated id seems to be pretty generic and maybe that's where the conflict is.

`+ id:                     "vpc-REDACTED_THE_AUTOGENERATED_CHARACTERS--default"`

**Comment by dentarg** [comment]
@mpichette We have identified a bug on our side in regards to `peer_network_uri`. The issue you're seeing happens when `peer_network_uri` is set to the full URI 

    https://www.googleapis.com/compute/v1/projects/PROJECT_NAME/global/networks/VPC_NETWORK_NAME

but not if you set `peer_network_uri` to just

    projects/PROJECT_NAME/global/networks/VPC_NETWORK_NAME

So that's the workaround we an offer right now. We will adjust the backend to handle both cases. Leaving this issue open to track that.

**Comment by mpichette** [comment]
Thank you! I'll give that a try!

**Comment by mpichette** [comment]
Made the change but now getting a 400 timeout.

`cloudamqp_vpc_gcp_peering.vpc_peering_request: Creating...
cloudamqp_vpc_gcp_peering.vpc_peering_request: Still creating... [10s elapsed]
cloudamqp_vpc_gcp_peering.vpc_peering_request: Still creating... [20s elapsed]
╷
│ Error: request VPC peering failed, status: 400, message: map[error:Timeout talking to backend]`

**Comment by dentarg** [comment]
@mpichette that's unfortunate... does it go through if you re-run?

We're actively working on handling this better (https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/243) but unfortunately I have no workaround to offer for that problem right now.

**Comment by dentarg** [comment]
@mpichette Are you still having issues? If so, please write in to https://www.cloudamqp.com/support.html and we can take a closer look. Feel free to reference this issue.

**Comment by mpichette** [comment]
We're looking at using the private service connect feature now since we're kind of blocked. Any idea if there is a plan to add the private service connect features to Terraform so we can avoid clickops in the future?

**Comment by mpichette** [comment]
@dentarg want me to close this issue out since you have the linked issue for the 400 errors?

**Comment by dentarg** [comment]
We can keep this issue open until we have addressed the validation issue in our backend (https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/242#issuecomment-1836169842).

**Comment by tbroden84** [comment]
The two other issues mention in this thread have now been handled. In the latest release [v1.29.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.29.0)

- Updated and added more functionality to the VPC peering for GCP. To avoid `Timeout talking to backend`.
- There is a new resource `cloudamqp_vpc_connect` that can be used for GCP Private Service Connect.

**Comment by tbroden84** [comment]
@mpichette We have now patched this in our backend and will close the issue. Please feel free to re-open the issue again if you experience any problem related to the GCP Peering.
