### ISSUE TITLE
Suddenly getting `subscription plan: lemming is not valid`

### ISSUE THREAD

**Issue by floge07** [cloudamqp/terraform-provider-cloudamqp#259]
Terraform Version: 1.7.3
Cloudamqp Provider Version: 1.29.3

Reached the limit of free instances in my Cloudamqp Team. Which I wasn't aware it was a thing. The error message the provider gave me also didn't help:

```
Error: 1 error occurred:
│ 	* subscription plan: lemming is not valid
```

Unsure if this limit is mentioned anywhere on the normal web UI since I only ever created cloudamqp resources via terraform. So it probably would be good to mention it on the [plans page](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/guides/info_plan).

Also, I don't think it is that great that this error is aborting the `terraform plan` step.
Although I understand that the goal is probably that the `apply` shouldn't suddenly fail if the plan was successfully made.

**Comment by tbroden84** [comment]
Hi, 

Yes, we have an upper limit on how many free plans we allow per team. Look like you hit this threshold. 
From the provider version [v1.26.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.26.0) released in May 2023, we started to validate `plan` and `region` to our API backend. This is done every time during the planning step when a new `cloudamqp_instance` is created or when the plan has changed.

Please email support at cloudamqp.com with more information about your team/user and we can double check this.

**Comment by floge07** [comment]
Hi,

we for sure have currently hit that free instance limit. Now that we figured out that this is the cause our PM is going to get in contact, but that is a private discussion.

On my part, I kinda have to figure out now how to get our infrastructure pipeline working again. 
That for_each on the `cloudamqp_instance` is based on - let's call it - runtime data.

So I can't just so easily delete those "items" again. (This whole thing might be highlighting some weaknesses in our setup). Cleaning up others also doesn't seem to help. This error occurs as soon as we have 1 [create] with a free plan. This also prevents any other resource changes that are not even dependent on the cloudamqp_instances.

I think the experience when getting into this situation could be improved a bit.
The error message itself and I don't think it should fully abort the plan and apply.
Unsure how complex that would be, our situation tbf also seems like quite the edge case.

**Comment by dentarg** [comment]
Thanks for the feedback @floge07 – we're looking forward to hear from your PM

We agree that the experience in this situation could be better. The hard limit on free accounts is there to prevent abuse, but we're very open to adjust it for legitime use-cases. We can do better to communicate this.

I don't have good suggestion for how to workaround this in your setup, besides creating another team, but I suspect that isn't ideal for you. To unblock you right now, the limit has been raised. Can you check if your pipeline works now?

**Comment by dentarg** [comment]
If you have paid instances, you now get a higher limit. I will close this issue because there is no action to take in this repo.

The API could give a better error message when this happens, but it is not high priority to address right now.
