### ISSUE TITLE
Issues creating cloudamqp_integration_log (Datadog) related to tags

### ISSUE THREAD

**Issue by neurogoblin** [cloudamqp/terraform-provider-cloudamqp#276]
Related to #195, I think.

### The error
```
cloudamqp_integration_metric.datadog_v2: Creating...
cloudamqp_integration_log.datadog: Creating...
cloudamqp_integration_metric.datadog_v2: Creation complete after 1s [id=19200]
╷
│ Error: CreateIntegration failed, status: 400, message: map[errors:[map[tags:Incorrect format of tags, should be key=value,key2=value2]]]
│ 
│   with cloudamqp_integration_log.datadog,
│   on rabbitmq.tf line 12, in resource "cloudamqp_integration_log" "datadog":
│   12: resource "cloudamqp_integration_log" "datadog" {
```

### The relevant config bits
```hcl
data "cloudamqp_account" "all" {}

locals {
  rmq_instance = [for i in data.cloudamqp_account.all.instances : i if i.name == "production"][0]
}

# We do an additional lookup here because we want to get the rmq_version value for tagging
data "cloudamqp_instance" "rmq" {
  instance_id = tonumber(local.rmq_instance.id)
}

resource "cloudamqp_integration_log" "datadog" {
  instance_id = data.cloudamqp_instance.rmq.id
  name        = "datadog"
  region      = var.datadog_region
  api_key     = var.datadog_api_key

  # Unified Service Tagging https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/
  # Format found at https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/6fd798bbeeaae8cf7598dd866c28a5d144c28d00/cloudamqp/resource_cloudamqp_integration_log_test.go#L45
  tags = join(",", ["env=production", "service=amqp", "version=${data.cloudamqp_instance.rmq.rmq_version}"])
}

resource "cloudamqp_integration_metric" "datadog_v2" {
  instance_id = data.cloudamqp_instance.rmq.id
  name        = "datadog_v2"
  api_key     = var.datadog_api_key
  region      = var.datadog_region
}
```

First, I confirmed that I'm making the tags in the correct format:
```
tags = join(",", ["env=production", "service=amqp", "version=${data.cloudamqp_instance.rmq.rmq_version}"])
```

The schema in the provider has `schema.TypeString`, and the test also has the same stringified `key=value,...` format.

I'm unsure exactly where this is failing, but I'm going to see if I can hack on the provider a bit locally and get more info.

**Comment by powerpointturingmachine** [comment]
I think it's related to [this part of the code for metrics](https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/6fd798bbeeaae8cf7598dd866c28a5d144c28d00/cloudamqp/resource_cloudamqp_integration_metric.go#L179-L193) but [no similar code exists for log](https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/6fd798bbeeaae8cf7598dd866c28a5d144c28d00/cloudamqp/resource_cloudamqp_integration_log.go#L206)

**Comment by powerpointturingmachine** [comment]
I believe the issue may be in the underlying API server receiving the calls. Unfortunately, I've not been able to test this with curl or HTTPie as I'm getting a 401 unauthorized response despite using the same API key as I have in Terraform.

I will try to provide more information about the direct API call's behavior once support has me set straight.

**Comment by tbroden84** [comment]
@neurogoblin 
Did some investigation, our internal validation follows: https://docs.datadoghq.com/getting_started/tagging/#define-tags
So it will fail using `version=3.x`, due that tags for Datadog must start with a letter like `version=v3.x`. See that this information is missing from our documentation and improvements can be made.
