### ISSUE TITLE
cloudamqp_integration_metric for datadog api_key should be sensitive value

### ISSUE THREAD

**Issue by mariot8** [cloudamqp/terraform-provider-cloudamqp#285]
datadog's api key should be stored as a sensitive value
https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/8fc908293b8ce606fdf379f094723b8297e25917/cloudamqp/resource_cloudamqp_integration_metric.go#L64

**Comment by tbroden84** [comment]
Yes correct, will make a fix for this.

**Comment by tbroden84** [comment]
@mariot8 Which version do you use? We changed this in the current released version (v1.30.0), in part of introducing Go_VCR testing.
https://github.com/cloudamqp/terraform-provider-cloudamqp/commit/8496cbf2ccad21f336e6ff665af95f57fc008e93#diff-371b79d5b90be285282a545145e7ce018c7eb6568222a1b53c776b95fa679224

**Comment by mariot8** [comment]
sorry for the late response, thanks for the fix
we'll try to upgrade the provider then
