### ISSUE TITLE
Add nodes internal address information

### ISSUE THREAD

**Issue by yurii-kryvosheia** [cloudamqp/terraform-provider-cloudamqp#286]
`cloudamqp_nodes` data exposes only hostname of the nodes of rabbitmq cluster that by default resolves to public IPs.
It would be nice to have internal_hostname attribute of every node in a cluster. 
```
{
  "id" = "999999"
  "instance_id" = 999990
  "nodes" = tolist([
    {
      "additional_disk_size" = 0
      "configured" = true
      "disk_size" = 4
      "erlang_version" = "26.2.5"
      "hipe" = false
      "hostname" = "xyz-maroon-cat-01.rmq3.cloudamqp.com"
      "name" = "xyz-maroon-cat-01"
      "rabbitmq_version" = "3.13.2"
      "running" = true
    },
  ])
}
```
I.e.
`"internal_hostname" = "xyz-maroon-cat-01.in.rmq3.cloudamqp.com"`

**Comment by tbroden84** [comment]
@yurii-kryvosheia There is now a new release [v1.30.1](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.30.1) with `hostname_internal` available for all nodes.

Closing the issue, feel free to re-open if there are any more questions.
