### ISSUE TITLE
Can't import the cloudamqp_vpc_gcp_peering terraform resource

### ISSUE THREAD

**Issue by akorzynski** [cloudamqp/terraform-provider-cloudamqp#307]
Hello,

We're writing up our existing CloudAMQP configuration in Terraform and we've encountered a snag: the cloudamqp_vpc_gcp_peering resource doesn't support importing an existing resource. As a result, we would need to destroy and re-create the VPC peering in order to "import" that configuration resource to Terraform, a process that would require downtime. Are you planning to implement the import feature for that resource in the cloudamqp Terraform provider?

Here is a link to the documentation:
https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/vpc_gcp_peering#import

Best regards,
Aleksander

**Comment by tbroden84** [comment]
@akorzynski 
Just released a new version [1.32.2](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.32.2) adding the import. Will close this issue, please feel free to re-open if there is any issues.
