### ISSUE TITLE
Pre-compiled Windows binaries in official releases

### ISSUE THREAD

**Issue by tylerohlsen** [cloudamqp/terraform-provider-cloudamqp#32]
Please also provide pre-compiled binaries for Windows with each release :)

**Comment by tbroden84** [comment]
Extended support in makefile for cross compile windows releases. Have not yet tested the provider to see if it works, but added the latest compile here. 

[terraform-provider-cloudamqp_v1.2.1_windows_386.tar.gz](https://github.com/cloudamqp/terraform-provider-cloudamqp/files/3933398/terraform-provider-cloudamqp_v1.2.1_windows_386.tar.gz)
[terraform-provider-cloudamqp_v1.2.1_windows_amd64.tar.gz](https://github.com/cloudamqp/terraform-provider-cloudamqp/files/3933399/terraform-provider-cloudamqp_v1.2.1_windows_amd64.tar.gz)

**Comment by tylerohlsen** [comment]
It's common practice to name the terraform provider binary targeted to Windows with the `.exe` file extension.  Though with our without the extension technically works.

Thanks for adding this so quickly!
