### ISSUE TITLE
Version 1.2.1 Git tag does not match pattern used in previous versions

### ISSUE THREAD

**Issue by jtrh** [cloudamqp/terraform-provider-cloudamqp#33]
The Git tag of the latest version contains a `.` between the `v` and the major version, while the previous version does not. This causes issues with automated download scripts.

- Version `1.2.1` is tagged with `v.1.2.1`: https://github.com/cloudamqp/terraform-provider-cloudamqp/tree/v.1.2.1
- Version `1.2.0` is tagged with `v1.2.0`: https://github.com/cloudamqp/terraform-provider-cloudamqp/tree/v1.2.0

**Comment by tbroden84** [comment]
My bad, updated both 1.2.0 and 1.2.1 releases with the correct tags.
