### ISSUE TITLE
Release into official providers

### ISSUE THREAD

**Issue by ralbertazzi** [cloudamqp/terraform-provider-cloudamqp#41]
I know nothing about the release process, but wouldn't it be beneficial if this provider could be installed just like [official Terraform providers](https://www.terraform.io/docs/providers/index.html)? I think that the manual installation and compilation is a big obstacle that prevents this library to be more used by devs

**Comment by pmichna** [comment]
@ralbertazzi https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/13

**Comment by ralbertazzi** [comment]
My bad! But thanks for having started the work :)
