### ISSUE TITLE
Add support for integrations

### ISSUE THREAD

**Issue by robmp** [cloudamqp/terraform-provider-cloudamqp#44]
Please add support for managing log and metrics integrations.
Looks like these already exist in the http api (at least partially).

**Comment by tbroden84** [comment]
Can investigate this next week.

**Comment by tbroden84** [comment]
Have created a draft for the integration and will need to test this out. But should be finished today.

**Comment by tbroden84** [comment]
Have now released a new release v1.6.0 that enables log and metric integrations through our API. The documentation can be found at:

- https://docs.cloudamqp.com/cloudamqp_terraform.html#integration-log
- https://docs.cloudamqp.com/cloudamqp_terraform.html#integration-metric
