### ISSUE TITLE
Doesn't seem to be deleting instances

### ISSUE THREAD

**Issue by wzcolon** [cloudamqp/terraform-provider-cloudamqp#5]
![image](https://user-images.githubusercontent.com/2379695/50234085-e4287800-0382-11e9-987a-acc9e1097cd0.png)

Takes 0 seconds and the instance is still present in the admin UI.

**Comment by tbroden84** [comment]
Closing this issue. Delete response from our underlying API behaves like this. Instant removed in our system and currently no way for our TF provider to follow up on the deletion progress that has been triggered. Updates have been done to ensure that the instances are deleted properly.
