### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [cloudamqp/terraform-provider-cloudamqp#54]
I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the master branch at git commit `f2f72f4`

- [ ] The resource file naming convention is as follows, `resource_providername_resource_name.go` which means the file `resource_instance.go` should be named `resource_cloudampq_instance.go` and its corresponding acceptance test should be named `resource_cloudampq_instance_test.go` , this should be follows across all resource files. 

- [ ] Your makefile should be updated with the GNUmakefile which is standard across all Terraform providers, feel free to copy the [GitHub provider makefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=clouldampq

- [ ] Along with the makefile, there are a few more scripts that are needed for testing and building the provider integration. You’ll need to add [changelog-links.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/changelog-links.sh) and [gogetcookie.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/gogetcookie.sh) to you scripts/ directory. 

- [ ] The website documentation should be written and put in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html). Each resource and data source will have its own page with arguments, attributes, usage examples and another useful documentation for   these are all written in markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example. 
-The Terraform.io website uses our terraform-website/ repository that is used as the middleman to sync all the terraform and provider documentation from all of their own repositories. To deploy the website locally follow the steps outlined in the README.
	- Once you've synced the current submodules there are 3 more steps required for adding you provider
	- Add the clouldampq provider as a submodule to the terraform-website/ directory with: `git submodule add -b master https://github.com/clouldampq/terraform-provider-clouldampq ext/providers/clouldampq`
	- Then you'll have to create two symbolic links to this module, first change to the working directory terraform-website/content/source/docs/providers/ the run: `ln -s ../../../../ext/providers/clouldampq/website/docs clouldampq`
	- And then change to the working directory to "terraform-website/content/source/layouts/" to run: `ln -s ../../../ext/providers/clouldampq/website/clouldampq.erb`
	- After those additions, you can then run the "make website" target to spin up the website using Docker desktop. 

- [ ] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in each TF providers. 

- [ ] The changeling you have is good, but there is a specific format that the log must be in because we have a bot have add the date after the version number during the release process. So the first line of your changelog should be `## 1.6.0 (Unreleased)`. If that’s the version number you want to release at. 

- [ ] I ran into a number of issues with the acceptance tests and attached the output below. It looks like some privilege issue with the credentials. [output.txt](https://github.com/cloudamqp/terraform-provider-cloudamqp/files/4578526/output.txt)

Let me know if you have any questions.

Best,
Chris

**Comment by tbroden84** [comment]
Thanks very much for the feedback. Will finish my current task then start to go over your points.

**Comment by tbroden84** [comment]
1. Renamed the data source and resource files to follow, resource_cloudamqp_<feature>.go
2. Changed Makefile to GNUMakefile. (Added internal version through -ldflags, we use it internally for the useragent.)
3. Add additional script files.
4. Added documentation over the provider and tried it out locally with your description.
5. Have re-enabled vendors and downloaded all dependencies.
6. Changed the top format. 
7. When I created your account I gave you the wrong permissions. You should now have full access to create, edit and remove instances. 

Overall went over the majority of the code and tried to clean it up, also run the go-linter for some extra pointers. Also found some issue in acceptance test that caused some of the test to fail.

A question regarding the changelog. Can I add date to it or should I leave it as unrelased? `## 1.7.0 (Jun, 8, 2020)` vs `## 1.7.0 (Unreleased)`. Also assume I don't need to make my own releases once it's approved. For my understanding updates will occur through pull request from our side to yours.

**Comment by cgriggs01** [comment]
Hi @tbroden84, 

For the changelog you'll need to be (Unreleased) for our release process to run. The  current date will be added 
 by a bot when the release is built and published. 

Everything else checks out so far. Im going to begin the migration and release process for the partner provider program which will go as follows:
- A repository under the same name `terraform-providers-cloudamqp` will be created in the  [github.com/terraform-repositories/](http://github.com/terraform-repositories/)  organization. 
- Your provider code will be pushed up to the new repository
- The binaries during release are pulled from the master branch. 
- A `stable-website` branch will be created, this is where the  [terraform.io](http://terraform.io/)  provider documentation is source from. During each release, a bot will commit the changes in your master branch to the stable-website branch. If you need to make changes to the provider website docs in between releases, you can cherry-pick the commits to the stable-website branch. 
- The first release will be tagged `1.7.2` per the CHANGELOG.md, or you can add new version number if you'd prefer. 
- You and whomever else on your team will be granted “write” access over the new repository are you are still seen as the owners and maintainers of the provider, before I grant you access, you’ll must review and agree to our community guidelines, which I’ll include below. 
- Whomever is added as a maintainer to the provider repository will also be granted an account on our #committers-terraform Slack channel, where you will request new versioned releases of the provider. 

Let me know if you have any questions. 

Community Guidelines and Etiquette 
We value our community contributors and their time and generally tend to avoid setting any particular obligations, however before you do participate in the community as a maintainer we kindly ask you to read the maintainer etiquette document: https://github.com/hashicorp/terraform/blob/master/docs/maintainer-etiquette.md. This document was written specifically for Terraform core, so the requirement for PR approval by a HashiCorp engineer is not needed as you develop your provider moving forward. 

Communicating on GitHub can sometimes be challenging. We expect our community to follow the guidelines at https://www.hashicorp.com/community-guidelines/, and for maintainers to lead as examples in that context. Please take time to review those guidelines, unless you have done so already.

Lastly, we want our contributors and their accounts to be safe, especially when accessing GitHub. Please make sure you have 2FA enabled for your account. If not, here's how to proceed: https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/

**Comment by tbroden84** [comment]
Hi @cgriggs01 

Thanks for taking time to help out with this. My bad to not add you on my former post. 

1. ok
2. Are we responsible for pushing to the new repository or will you guys do it? A lot of features in git I still learning. 
3. ok
4. ok
5. I had some commits suitable for a 1.7.3 release. But also added 1.8.0 (Unreleased) as new fresh start to the CHANGELOG. I assume I don't need to do a proper release on 1.8.0.
6. Yes I will be responsible. We have discussed to bring in another developer too, but not decided yet. Have reviewed and agree to the community guidelines. 
7. ok, will be me. So if I understand this correct, when we do further development on our provider, handle issues or dealing with PR. We still work against our own repository. Then when a new release is ready, make a request on slack?

I also had 2FA enabled from before.

**Comment by cgriggs01** [comment]
Hi @tbroden84,

2. No, I will push up the new code and trigger the first release. 
5. Perfect, thanks for making those changes. I'll trigger a 1.8.0 release. 
6. You should see an invite to the repository and our Slack channel soon. 
7. Yes, when you are ready to publish a new release, make sure changes are merged into the master branch, then request the release through the slack channel. 

Starting the process now and we should complete it tomorrow.

**Comment by tylerohlsen** [comment]
Was the new repository created?  Is it private?  Because I cannot see it.  
(I'm just looking to add a _watch_ for releases)

**Comment by tylerohlsen** [comment]
Nevermind, found it: https://github.com/terraform-providers/terraform-provider-cloudamqp/releases

**Comment by tbroden84** [comment]
No longer viable, due to Terraform Registry.
