### ISSUE TITLE
Never recognizes newly created instance. Stalls TF script.

### ISSUE THREAD

**Issue by wzcolon** [cloudamqp/terraform-provider-cloudamqp#6]
![image](https://user-images.githubusercontent.com/2379695/50345287-891a9080-04fc-11e9-90b2-ac44459d9302.png)

More often than not, the script never returns from creating a new CloudAMQP instance. The new instance was created though.

```
provider "cloudamqp" {
  apikey = "${var.cloud_amqp_api_key}"
}

resource "cloudamqp_instance" "rmq_bunny" {
  name   = "test-rabbitmq"
  plan   = "tiger"
  region = "amazon-web-services::us-east-1"
}

**Comment by noqcks** [comment]
I would like to confirm that this is still happening.

**Comment by tbroden84** [comment]
Closing this issue. Due to older version and have been solved indirectly with newer versions.
