### ISSUE TITLE
provide binaries in releases

### ISSUE THREAD

**Issue by philipp-hb** [cloudamqp/terraform-provider-cloudamqp#62]
for easier use of new versions of the provider, I'd suggest to provide binaries of the releases, so the user doesn't need to build them.

**Comment by tbroden84** [comment]
Yes did it before until v1.7.0 when I removed the makefile. Since v1.3.0 when we changed dependency management it made it easier to build. Requires on the other hand a working GNUmakefile. 

Did however update the latest release with binaries too.

**Comment by philipp-hb** [comment]
Thank you. I tried the binary and it works like a charm
feel free to close this issue (or leave it open, if you'd like to provide binaries for every release and haven't automated it yet)
