### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by FGRibreau** [cloudamqp/terraform-provider-cloudamqp#70]
Any plan to add webhook support?

It's the last thing that that we miss with this provider :)

**Comment by tbroden84** [comment]
The initial plan was to make everything available as from web ui. But some of the features have been overlooked. Good you reminds us on the features we missed. Due to vacations this will need to be looked at in the beginning of August.

**Comment by FGRibreau** [comment]
Awesome, thanks!

**Comment by tbroden84** [comment]
This issue was never closed. Please see https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/webhook
