### ISSUE TITLE
Error while creating Datadog logs integration (v1.8.0)

### ISSUE THREAD

**Issue by robmp** [cloudamqp/terraform-provider-cloudamqp#75]
When creating the resource:
```terraform
 resource "cloudamqp_integration_log" "datadog" {
   instance_id = cloudamqp_instance.instance.id
   name        = "datadog"
   region      = "us"
   api_key     = var.datadog_api_key
   tags        = "environment=${var.environment},instance=${cloudamqp_instance.instance.name}"
 }
```
we got
```
Error: error setting type for resource 4537: Invalid address to set: []string{"type"}
```
The integration was created correctly despite the error, but the error is now thrown on all subsequent plans.

**Comment by robmp** [comment]
Terraform v0.12.29

**Comment by tbroden84** [comment]
There is a fix for this in v1.8.1 released here as a customer provider. Have not yet manage to update our official provider with this.

**Comment by yashbhutwala** [comment]
Hello @tbroden84, I'm also facing this.  What is the update on this?  Anything I can do to help make progress on it.  Thanks!

**Comment by yashbhutwala** [comment]
When does the difference between this repo and https://github.com/terraform-providers/terraform-provider-cloudamqp get cleared up?

**Comment by dentarg** [comment]
I think this has been solved. Let us know if not and we can re-open (or feel free to open a new issue).
