### ISSUE TITLE
New plans and options

### ISSUE THREAD

**Issue by magikid** [cloudamqp/terraform-provider-cloudamqp#79]
Yesterday, CloudAMQP [released new plans](https://www.cloudamqp.com/blog/2020-11-02-new-and-updated-cloudamqp-plans.html).  There are two new plans (Sassy Squirrel and Raging Rhino) and several others have changed names.  Plans can also have clusters of 5 nodes and the 2 node plan has been removed.

**Comment by tbroden84** [comment]
Available from v1.9.0.
