### ISSUE TITLE
Allow managing RabbitMQ version

### ISSUE THREAD

**Issue by yashbhutwala** [cloudamqp/terraform-provider-cloudamqp#82]
Currently, rabbitmq version cannot be managed and upgrade with this terraform provider

Migrated from https://github.com/hashicorp/terraform-provider-cloudamqp/issues/5 since that repository is archived now.

**Comment by tbroden84** [comment]
Have had internal discussion about this, to automate the upgrade of both RMQ and Erlang versions. So far only prototype solutions but no real one found.  One way could be to allow the updates to occur similar as our console, but also have its risks.

**Comment by yashbhutwala** [comment]
OK sounds good, thanks @tbroden84 for the open communication.  Another thing that's relevant for which I have a ticket with CloudAMQP support team is that currently with just the CloudAMQP API, there is no way to determine if configuration change can be performed for the server at any given time, i.e.:  if I'm make the API call to upgrade erlang version, there is not an explicit API call I can make to know if that operation has completed; so if I fire the erlang upgrade, and then if I try to fire the upgrade rabbitmq immediately, I get a 500.  Hopefully, that API could help as well.

**Comment by philipp-hb** [comment]
it would be really great if RMQ and Erlang versions could be managed using Terraform. We got quite a bunch of clusters and clicking through each of them is quite a pain

**Comment by torbendury** [comment]
Beside the [Changelog](https://cloudamqp.com/changelog.html), is there an API to get available versions for instance XY?

**Comment by dentarg** [comment]
> Beside the [Changelog](https://cloudamqp.com/changelog.html), is there an API to get available versions for instance XY?

@torbendury there is now! See "Get available versions" at https://docs.cloudamqp.com/cloudamqp_api.html#nodes

**Comment by tbroden84** [comment]
We have now released a new version [v1.17.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.17.0) and added support to automatically upgrade both RabbitMQ and Erlang versions to latest possible upgradable versions.

Reason both are upgraded in the same go, is to avoid mismatch in required Erlang version depending on RabbitMQ version. From current versions used, it's possible to check which possible versions the upgrade will upgrade to.

* As data source [cloudamqp_upgradable_versions](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/data-sources/upgradable_versions)
* From our backend [API](https://docs.cloudamqp.com/cloudamqp_api.html#fetch-what-versions-rabbitmq-erlang-upgrade-will-upgrade-to)

Then to actually trigger the upgrade

* From resource [cloudamqp_upgrade_rabbitmq](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/upgrade_rabbitmq)

Note: Depending on current versions used, `cloudamqp_upgrade_rabbitmq` may need to be triggered multiple times. 

Pull request for this feature [#151](https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/151)
