### ISSUE TITLE
ReadFirewallSettings 400 when executing `terraform plan`

### ISSUE THREAD

**Issue by parmouraly** [cloudamqp/terraform-provider-cloudamqp#88]
**Describe the bug**
`terraform plan` can occasionally fail with this error

`Error: ReadFirewallSettings failed, status: 400, message: map[error:Timeout talking to backend]`

**To Reproduce**
It's hard to consistently reproduce this as it seems to be happening randomly.
If you executed plan in a loop chances are you'd eventually hit this issue.

**Expected behavior**
Plan should consistently work and avoid this error.

**Additional context/analysis**
At a guess this seems to be the request failing
https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/master/cloudamqp/resource_cloudamqp_security_firewall.go#L95
and
https://docs.cloudamqp.com/cloudamqp_api.html#firewall

**Suggested solution**
Not sure what would be the best approach here, but assuming the API call can occasionally fail, perhaps would be worth a configurable retry logic?

**Comment by dentarg** [comment]
Sorry about this, it shouldn't really happen, but unfortunately it has been a problem lately. These incidents probably caused the error you saw: https://status.cloudamqp.com/incidents/4ptsm6jg7775, https://status.cloudamqp.com/incidents/h5wpv8sqdsm0 (there can also have been shorter incidents not listed on the status page). We are working on making the backend more stable. Again, apologies!

I'll let @tbroden84 comment on if we need any retry logic. I assume we would appreciate a PR :-)

**Comment by parmouraly** [comment]
Hey @dentarg thanks for the quick reply on that and sharing the status links. The timing matches the latest errors we had indeed. 
I'd be more than happy to PR smth on this but wanted to raise an issue first to double check what your thoughts are.

Considering these errors are probably related to the incidents you mention, I'm no longer convinced a retry would solve this as I assume incidents last for more than a few seconds or even minutes and we wouldn't be able or even want to hold a `plan` going for the duration of the incident.
At least that's my first thought on this.

**Comment by dentarg** [comment]
I agree with your thoughts @parmouraly, so perhaps we can close this issue? The backend issues should have been sorted out last week.
