### ISSUE TITLE
error setting no_default_alarms for resource

### ISSUE THREAD

**Issue by robinvdvleuten** [cloudamqp/terraform-provider-cloudamqp#98]
When I use the `cloudamqp_instance` data source, I get the following error on Terraform;

```
error setting no_default_alarms for resource ***: Invalid address to set: []string{"no_default_alarms"}
```

Looks like an internal type is invalid?

**Comment by dentarg** [comment]
Can you give a more complete example? Or [contact our support](https://www.cloudamqp.com/support.html) and share the name of your instance so we can look into it. Thanks.

**Comment by robinvdvleuten** [comment]
Sure! I create in one workspace a CloudAMQP instance like this;

```tf
resource "cloudamqp_instance" "this" {
  name   = local.name
  plan   = var.cloudamqp_plan
  region = "amazon-web-services::${data.aws_region.current.name}"
}
```

And then in a separate workspace, I try to access the instance by creating a data source like this;

```tf
data "cloudamqp_instance" "this" {
  instance_id = var.cloudamqp_instance_id
}
``` 

But then I run into this `no_default_alarms` issue.

**Comment by robinvdvleuten** [comment]
The CloudAMQP instance is created as expected btw, but I cannot use it as a data source.
