### ISSUE TITLE
Error setting plugins while using datasource cloudamqp_plugins

### ISSUE THREAD

**Issue by andreykaipov** [cloudamqp/terraform-provider-cloudamqp#99]
Minimum working example:
```hcl
terraform {
  required_providers {
    cloudamqp = {
      source  = "cloudamqp/cloudamqp"
      version = "~> 1.9"
    }
  }
}

data "cloudamqp_plugins" "plugins" {
  instance_id = 123456
}

output "plugins" {
  value = data.cloudamqp_plugins.plugins
}
```

```console
❯ terraform init
❯ CLOUDAMQP_APIKEY=blah terraform apply
╷
│ Error: error setting plugins for resource 125607.plugins: Invalid address to set: []string{"plugins", "0", "blocked"}
│
│   with data.cloudamqp_plugins.plugins,
│   on main.tf line 10, in data "cloudamqp_plugins" "plugins":
│   10: data "cloudamqp_plugins" "plugins" {
│
╵
❯ terraform version
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/cloudamqp/cloudamqp v1.9.2
```

**Comment by andreykaipov** [comment]
This seems to be because the datasource schema doesn't properly ignore the null fields from the API response. Specifically, compare [the existing schema](https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/v1.9.2/cloudamqp/data_source_cloudamqp_plugins.go#L24-L43) with the following:

```console
❯ curl -sku :blah https://customer.cloudamqp.com/api/instances/123456/plugins | jq .[0]
{
  "name": "rabbitmq_amqp1_0",
  "version": "3.8.14",
  "description": "AMQP 1.0 support for RabbitMQ",
  "enabled": false,
  "recommended": null,
  "blocked": null
}
```

The `recommended` and `blocked` keys are not part of the schema and the error is returned.

--- 

If we reproduce the above MWE using `cloudamqp_plugins_community`, we'll find it works okay because its API response matches [the schema](https://github.com/cloudamqp/terraform-provider-cloudamqp/blob/v1.9.2/cloudamqp/data_source_cloudamqp_plugins_community.go#L24-L40):

```console
❯ curl -sku :blah https://customer.cloudamqp.com/api/instances/123456/plugins/community | jq .[0]
{
  "name": "rabbitmq_lvc_exchange",
  "description": "The last value exchange acts like a direct exchange (binding keys are compared for equality with routing keys); but it also keeps track of the last value that was published with each routing key, and when a queue is bound, it automatically enqueues the last value for the binding key.",
  "require": "3.6.0"
}
```

**Comment by dentarg** [comment]
@andreykaipov Thanks for the investigation here, will work with @tbroden84 on addressing the issue

**Comment by dentarg** [comment]
@andreykaipov I think the latest release, https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.9.4, addressed this issue (I can run your example above). Let us know if not and we can investigate more!
